# Kafka broker configuration
mp.messaging.incoming.kafka-predictions.group.id=flair-consumer-${uuid}
mp.messaging.incoming.kafka-predictions.auto.offset.reset=earliest
mp.messaging.incoming.kafka-predictions.enable.auto.commit=false
mp.messaging.incoming.kafka-predictions.connector=smallrye-kafka
mp.messaging.incoming.kafka-predictions.topic=kafka-predictions
mp.messaging.incoming.kafka-predictions.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.kafka-predictions.bootstrap.servers=reddit-posts-kafka-bootstrap.reddit-realtime.svc:9093

# Enable Prometheus metrics
quarkus.micrometer.export-prometheus.enabled=true
quarkus.micrometer.export-prometheus.path=/q/metrics

# OpenTelemetry tracing
quarkus.application.name=flair-consumer
quarkus.otel.exporter.otlp.endpoint=http://jaeger.reddit-realtime.svc:4317
quarkus.otel.exporter.otlp.traces.protocol=grpc
