apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quarkus-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: predictions-consumer
  endpoints:
    - port: http
      path: /q/metrics
      interval: 15s
