apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: reddit-realtime
  labels:
    strimzi.io/cluster: reddit-posts
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: reddit-posts
  namespace: reddit-realtime
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    replicas: 1
    listeners:
      - name: plain
        type: internal
        port: 9093
        tls: false
      - name: external  # NEW: Exposing Kafka externally
        type: nodeport  # Use LoadBalancer if in cloud
        port: 9094
        tls: false
    config:
      offsets.topic.replication.factor: 1
    storage:
      type: ephemeral