apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: reddit-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: quay.io/carlesarnal/reddit-posts-processor:sha-5cf65a9
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              value: "reddit-posts-kafka-bootstrap.reddit-realtime.svc:9093"
            - name: REDDIT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: reddit-api-credentials
                  key: client-id
            - name: REDDIT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: reddit-api-credentials
                  key: client-secret
            - name: REDDIT_USER_AGENT
              value: "predictions"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - pgrep
                - -f
                - reddit_posts_processor
            initialDelaySeconds: 30
            periodSeconds: 30
