apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: reddit-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: docker.io/library/reddit-producer:local
          imagePullPolicy: Never
          env:
            - name: KAFKA_BROKER
              value: "reddit-posts-kafka-bootstrap.reddit-realtime.svc:9093"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - pgrep
                - -f
                - reddit_posts_processor
            initialDelaySeconds: 30
            periodSeconds: 30
