apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictions-consumer
  namespace: reddit-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictions-consumer
  template:
    metadata:
      labels:
        app: predictions-consumer
    spec:
      containers:
        - name: predictions-consumer
          image: quay.io/carlesarnal/predictions-publisher:sha-7bc39b5
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger.reddit-realtime.svc:4317"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: predictions-consumer
  namespace: reddit-realtime
spec:
  selector:
    app: predictions-consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080