apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictions-consumer
  namespace: reddit-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictions-consumer
  template:
    metadata:
      labels:
        app: predictions-consumer
    spec:
      containers:
        - name: predictions-consumer
          image: quay.io/carlesarnal/predictions-publisher:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: predictions-consumer
  namespace: reddit-realtime
spec:
  selector:
    app: predictions-consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080