apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-reddit-inference
  namespace: spark-operator
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: quay.io/carlesarnal/spark-inference:sha-2e4c7d5
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/jobs/reddit_flair_spark_inference.py
  sparkVersion: 3.5.3
  driver:
    cores: 1
    memory: 3g
    serviceAccount: spark-operator-spark
    resources:
      requests:
        memory: "3Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
  executor:
    cores: 1
    instances: 1
    memory: 3g
    resources:
      requests:
        memory: "3Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
    labels:
      version: "3.5.0"