apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-reddit-inference
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: quay.io/carlesarnal/spark-inference:11
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/jobs/reddit_flair_spark_inference.py
  sparkVersion: 3.5.3
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 1
    memory: "1g"
    labels:
      version: "3.5.0"