apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  namespace: reddit-realtime
  name: spark-reddit-inference
spec:
  type: Python
  mode: cluster
  image: gcr.io/spark-operator/spark:v3.5.0
  mainApplicationFile: local:///opt/spark/jobs/reddit_flair_spark_inference.py
  sparkVersion: "3.5.0"
  driver:
    cores: 1
    memory: "512m"
  executor:
    cores: 1
    instances: 2
    memory: "1g"